### ISSUE TITLE
JSON files truncated

### ISSUE THREAD

**Issue by jleproust** [GossiTheDog/Monitoring#1]
Hello,

Thanks a lot for your work! I'd like to setup alerts using your monitoring, and I tried reading the target files as json, but most of them seem truncated at the end. I could fix with a PR, but there might be an issue with the file import process. Could you look into it? Additionally, using a json file extension instead of .txt would help exploring the files on github. I can help if you wish.

Best regards.

**Comment by GossiTheDog** [comment]
Hola!  Later versions should have the full values, apologies.
